project:
  type: website
  output-dir: "docs"

website:
  title: "carlos thayan"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Porfolio"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

