project:
  type: website
  output-dir: "docs"

website:
  title: "Carlos Thayan"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Posts"
        file: portfolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/carlosthayan
        target: _blank
      - icon: twitter
        href: https://x.com/thayan_moreira
        target: _blank
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

