project:
  type: website
  output-dir: "docs"

website:
  title: "carlos thayan"
  navbar:
    left: 
      - text: "Home"
      - text: "Porfolio"
      - text: "CV"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

